import { About, Clients, Footer, Header, Home, Road, Team, Token, White, Works } from '@/components'
import Head from 'next/head'

export default function index() {
  return (
    <>
      <Head>
        <title>Swaper - ICO, AirDrop and Swaper for Voilk Network.</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" type="image/x-icon" href="assets/images/favicon.png" />
      </Head>

      <Header />
      <Home />
      <Works />
      <About />
      <Token />
      <Road />
      <Team />
      <White />
      <Footer />
      <a href="#" class="scrollup btn-default" style={{ display: "none" }}><i class="ion-ios-arrow-up"></i></a>

    </>
  )
}
